---
- name: Configure common packages on all VMs
  hosts: all
  become: true
  roles:
    - common

- name: Configure monitoring control VM
  hosts: control
  become: true
  roles:
    - control

- name: Configure monitored nodes
  hosts: nodes
  become: true
  roles:
    - node
    - promtail